server:
  port: 8888

spring: 
  # 数据库驱动连接
  datasource: 
    # mysql8之后需要指定时区和安全连接方式
    url: jdbc:mysql://localhost:3306/javaweb?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: javaweb
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*.xml
